### ISSUE TITLE
nib_ls test failure on SPARC

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nibabel#422]
@yarikoptic - any thoughts on this one?

http://nipy.bic.berkeley.edu/builders/nibabel-py2.7-wheezy-sparc/builds/115

```
======================================================================
FAIL: nibabel.tests.test_scripts.test_nib_ls_multiple
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/nd-bb-slave-sparc64-wheezy/nibabel-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildslave/nd-bb-slave-sparc64-wheezy/nibabel-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/nibabel/tests/test_scripts.py", line 94, in test_nib_ls_multiple
    "Full output was: %s" % stdout_lines)
AssertionError: Type sub-string didn't start with 'i'. Full output was: [u'/home/buildslave/nd-bb-slave-sparc64-wheezy/nibabel-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/nibabel/tests/data/example4d.nii.gz      <i2 [128,  96,  24,   2] 2.00x2.00x2.20x2000.00  #exts: 2 sform', u'/home/buildslave/nd-bb-slave-sparc64-wheezy/nibabel-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/nibabel/tests/data/example_nifti2.nii.gz <i2 [ 32,  20,  12,   2] 2.00x2.00x2.20x2000.00  #exts: 2 sform', u'/home/buildslave/nd-bb-slave-sparc64-wheezy/nibabel-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/nibabel/tests/data/small.mnc             <i2 [ 18,  28,  29]      9.00x8.00x7.00', u'/home/buildslave/nd-bb-slave-sparc64-wheezy/nibabel-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/nibabel/tests/data/nifti2.hdr            <i2 [ 91, 109,  91]      2.00x2.00x2.00']
```

**Comment by matthew-brett** [comment]
Yarik - any thoughts on this one?

**Comment by yarikoptic** [comment]
I feel like I have fixed for smth like that before... what about https://github.com/nipy/nibabel/pull/437 and then I will double check/fix for this one, otherwise there might be conflicts etc  ;)?

**Comment by matthew-brett** [comment]
I think this error remains : http://nipy.bic.berkeley.edu/builders/nibabel-py2.7-wheezy-sparc/builds/134/steps/shell_5/logs/stdio

**Comment by yarikoptic** [comment]
looking into it, sorry about delay
